name: Build and Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - name: Install Rust
        run: |
          # pin to specific nightly version so cranelift work and cache is effective
          rustup toolchain install nightly-2025-04-03 --profile minimal --no-self-update
          rustup default nightly-2025-04-03
          rustup component add rustc-codegen-cranelift-preview --toolchain nightly-2025-04-03
      - uses: Swatinem/rust-cache@v2
      - run: cargo test
      - run: cargo build --release
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: target/release/disbot_v2

  release:
    needs: build
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: target/release
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: thanadolps/disbot_v2:latest
